snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: https://mngjssf-sv03311.snowflakecomputing.com
      user: PABLOSEBASTIAN
      password: Enrique44#
      role: SYSADMIN
      database: tastybytes_db
      warehouse: COMPUTE_WH
      schema: analytics
      threads: 4
      client_session_keep_alive: False
