version: 2

sources:
  - name: RAW_POS               
    database: TB_101            
    schema: RAW_POS                  
    tables:                      
      - name: TRUCK             
      - name: ORDER_DETAIL       
      - name: COUNTRY            
      - name: FRANCHISE          
      - name: LOCATION           
      - name: MENU               
      - name: ORDER_HEADER       
     

  - name: RAW_CUSTOMER           
    database: TB_101            # Ensure this is set to TB_101
    schema: RAW_CUSTOMER        # Make sure this is correct
    tables:                      
      - name: CUSTOMER_LOYALTY   
