version: 2

sources:
  - name: RAW_POS               
    database: RAW_POS            
    schema: raw                 
    tables:                      
      - name: TRUCK             
      - name: ORDER_DETAIL       
      - name: COUNTRY            
      - name: FRANCHISE          
      - name: LOCATION           
      - name: MENU               
      - name: ORDER_HEADER       

  - name: RAW_CUSTOMER           
    database: RAW_CUSTOMER       
    schema: raw                  
    tables:                      
      - name: CUSTOMER_LOYALTY   
